apiVersion: v1
kind: Pod
metadata: 
 name: nodeport
 labels:
  app: nginx-nodeport
  demo: service

spec:
 containers:
 - name: portnode
   image: nginx
   ports:
   - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
 name: nodeport

spec:
 type: NodePort
 selector: 
  app: nginx-nodeport
  demo: service
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80