apiVersion: v1
kind: Pod
metadata:
 name: taint-pod
 

spec:
 containers:
 - name: taint-pod
   image: nginx
   ports:
   - containerPort: 80
 tolerations:
 - key: project
   operator: "Exists"
   effect: NoSchedule