apiVersion: v1
kind: Pod
metadata:
 name: pod-config

spec:
 containers:
 - name: con-4
   image: nginx
   ports:
   - containerPort: 80
   env:
   - name: env
     valueFrom:
      configMapKeyRef:
       name: configmap
       key: name
   - name : ent
     valueFrom:
       configMapKeyRef:
        name: configmap
        key: occupation
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-1
spec:
  # list of containers
 containers:
  - name: config-pod-1
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
       name: pod-config